// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Human         string
	MigMigrations string
	NameRef       string
	VotedBallot   string
}{
	Human:         "human",
	MigMigrations: "mig_migrations",
	NameRef:       "name_ref",
	VotedBallot:   "voted_ballot",
}
